services:
  eurofoam:
    image: zahrbrixta/eurofoam-mattresses:latest
    container_name: eurofoam-mattresses
    restart: unless-stopped
    ports:
      - "55002:3000"
    environment:
      - CMS_DATA_DIR=/app/data
      #- ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
    volumes:
      - eurofoam_data:/app/data

volumes:
  eurofoam_data:



